### ISSUE TITLE
Fix requirements.txt

### ISSUE THREAD

**Issue by brucepro** [brucepro/Memoir#3]
Used pipreqs but it changes some of the versions needed for textgen, so better to build out manually.

**Comment by AbraKadabra1** [comment]
I was installing this s*it for 11 hours already, constantly stumbling into errors. And when i was almost there, you remove everything from requirements? I'm sorry, but you have no idea how frustrated I'm right now, can you at least send a list of what we need to install?

**Comment by datfoosteve** [comment]
i got this to work by installing using textgen webui session tab because i couldnt install it manually. Then using the textgen web ui's virtual environment accessed by 'cmd_windows.bat', i installed the missing requirements.

the list I pip installed is the following: 

1. python_on_whales
2. textblob
3. validators
4. qdrant_client
5. sentence_transformers

and it worked.

**Comment by AbraKadabra1** [comment]
Oh my god, thank you! It's finally working! I wasted so much time on that, but still, thank you both for extension and solution!

**Comment by datfoosteve** [comment]
did it work for you? i got it to load but it doesn't work for me

**Comment by datfoosteve** [comment]
i got it to work, i dont know why but the short term memory code never created a database folder in the storage directory. IT created a qdrant folder for long term memory, but not for short term. 

just by creating a folder in '\extensions\Memoir\storage'
named "sqlite",

i got the whole thing to finally work
